options:
  port: 8000 # Port to serve on (localhost:[port])
  outputDirectory: "serve" # Directory to generate files to
  reloadTime: 2 # Time between re-generating in seconds
  timeFormat: "%A, %b %d %I:%M"

customValues:
  demo: "If you can see this text, custom values are working!"
  looseBrackets: "If you can see this, loose brackets are working!"
